import { MarketSegment } from './types';

export const cannabinoidMarketData: MarketSegment = {
  id: "root",
  name: "Global Market",
  marketSize: "$500B",
  growthRate: "7.5% CAGR",
  keyMetric: "25% YoY Revenue Growth",
  profitMargin: "35%",
  customerAcquisitionCost: "$1,000",
  lifetimeValue: "$10,000",
  revenuePerEmployee: "$500,000",
  projectedGrowth: [500, 537.5, 577.8, 621.1, 667.7],
  children: [
    {
      id: "chronic-pain",
      name: "Chronic Pain Management",
      marketSize: "$80B",
      growthRate: "9.5% CAGR",
      keyMetric: "30% Reduction in Opioid Prescriptions",
      profitMargin: "40%",
      customerAcquisitionCost: "$2,000",
      lifetimeValue: "$50,000",
      revenuePerEmployee: "$600,000",
      projectedGrowth: [80, 87.6, 96.0, 105.1, 115.0],
    },
    {
      id: "cancer-treatment",
      name: "Cancer Treatment Side Effects",
      marketSize: "$70B",
      growthRate: "8.0% CAGR",
      keyMetric: "$1,200 Savings per Patient per Year",
      profitMargin: "35%",
      customerAcquisitionCost: "$1,800",
      lifetimeValue: "$45,000",
      revenuePerEmployee: "$550,000",
      projectedGrowth: [70, 75.6, 81.6, 88.1, 95.1],
    },
    {
      id: "anxiety-disorders",
      name: "Anxiety Disorders",
      marketSize: "$60B",
      growthRate: "10.0% CAGR",
      keyMetric: "$900 Savings on Benzodiazepines per Patient",
      profitMargin: "38%",
      customerAcquisitionCost: "$1,500",
      lifetimeValue: "$40,000",
      revenuePerEmployee: "$500,000",
      projectedGrowth: [60, 66.0, 72.6, 79.9, 87.9],
    },
    {
      id: "ptsd",
      name: "PTSD Management",
      marketSize: "$40B",
      growthRate: "7.0% CAGR",
      keyMetric: "20% Reduction in Psychiatric Medication Use",
      profitMargin: "30%",
      customerAcquisitionCost: "$2,200",
      lifetimeValue: "$35,000",
      revenuePerEmployee: "$400,000",
      projectedGrowth: [40, 42.8, 45.8, 49.0, 52.4],
    },
    {
      id: "sleep-disorders",
      name: "Sleep Disorders",
      marketSize: "$50B",
      growthRate: "9.0% CAGR",
      keyMetric: "15% Reduction in Prescription Sleep Aid Usage",
      profitMargin: "37%",
      customerAcquisitionCost: "$1,200",
      lifetimeValue: "$30,000",
      revenuePerEmployee: "$450,000",
      projectedGrowth: [50, 54.5, 59.4, 64.8, 70.6],
    },
    {
      id: "fibromyalgia",
      name: "Fibromyalgia",
      marketSize: "$45B",
      growthRate: "8.5% CAGR",
      keyMetric: "10% Reduction in Polypharmacy Costs",
      profitMargin: "36%",
      customerAcquisitionCost: "$1,700",
      lifetimeValue: "$28,000",
      revenuePerEmployee: "$420,000",
      projectedGrowth: [45, 48.8, 52.9, 57.4, 62.2],
    },
    {
      id: "neuropathic-pain",
      name: "Neuropathic Pain",
      marketSize: "$55B",
      growthRate: "8.7% CAGR",
      keyMetric: "$800 Savings per Patient on Anticonvulsants",
      profitMargin: "34%",
      customerAcquisitionCost: "$1,600",
      lifetimeValue: "$32,000",
      revenuePerEmployee: "$480,000",
      projectedGrowth: [55, 59.8, 65.0, 70.7, 76.9],
    },
    {
      id: "autism",
      name: "Autism Spectrum Disorders",
      marketSize: "$30B",
      growthRate: "7.8% CAGR",
      keyMetric: "$12,000 Reduction in Behavioral Intervention Costs",
      profitMargin: "32%",
      customerAcquisitionCost: "$3,000",
      lifetimeValue: "$50,000",
      revenuePerEmployee: "$300,000",
      projectedGrowth: [30, 32.3, 34.8, 37.5, 40.5],
    }
  ]
};
